stages:
  - build
  - scan

variables:
  CI_APP_NAME: 'api-wrapper'
  MAVEN_IMAGE: 'eclipse-temurin:17.0.3_7-jre-alpine'

maven:
  stage: build
  image: $MAVEN_IMAGE
  allow_failure: true
  script:
    - mvn verify -Djar.finalName=$CI_APP_NAME
  only:
    refs:
      - main
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
    paths:
      - target/*/**
    expire_in: 2 hours
