name: Icy Maven Java 17 Build

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      executable_location:
        required: true
        type: string


jobs:
  java17:
    name: Maven verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven verify
        run: mvn verify -Djar.finalName=${{ inputs.application_name }}
      - name: Create upload folder for artifacts
        run: mkdir staging && cp -r ${{ inputs.executable_location }} staging
