name: Snyk Security Tests

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: staging/${{ inputs.application_name }}
          path: staging/*
      - name: Snyk security tests
        uses: snyk/actions/maven-3-jdk-11@main
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
