name: Snyk Security Tests

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact # https://github.com/marketplace/actions/download-workflow-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ./.github/workflows/java17-temurin-maven-template.yml
          name: ${{ inputs.application_name }}
      - name: Snyk security tests
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
