name: Snyk Security Tests

on:
  workflow_call:
    secrets:
      auth-token:
        required: true

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk security tests
        uses: snyk/actions/maven-3-jdk-11@master
        with:
          auth-token: ${{ secrets.SNYK_TOKEN }}