server:
  port: 8080

spring:
  application:
    name: api-wrapper

api-wrapper-config:
  base-url: https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes
  host: spoonacular-recipe-food-nutrition-v1.p.rapidapi.com
